
services:
  backend:
    build: ./backend
    container_name: filmsite-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/APP
      - /APP/node_modules
    command: npm run dev

  frontend:
    build: ./filmsite-app
    container_name: filmsite-frontend
    ports:
      - "5173:5173"
    volumes: 
      - ./filmsite-app:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

  db:  
    image: postgres:16
    container_name: filmsitesi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: filmsitesi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: